	AREA RESET, DATA, READONLY
	EXPORT __Vectors
__Vectors
	DCD 0x40001000
	DCD Reset_Handler
	ALIGN
	AREA mycode, CODE, READONLY
	ENTRY
	EXPORT Reset_Handler
Reset_Handler
	LDR R0,=SRC
	LDR R1,=SRC1
	LDR R2,=RES
	LDR R0,[R0]
	LDR R1,[R1]
	MOV R3,R0
    MOV R4,R0
UP	SUB R3,R1
	CMP R3,R1
	BGE UP
	TEQ R3,#0
	BEQ LCM
	ADD R4,R0
	MOV R3,R4
	B UP
LCM	STR R4,[R2]	
STOP B STOP
SRC DCD 20
SRC1 DCD 150	
	AREA mydata, DATA, READWRITE
RES DCD 0
	END